version: '{build}'
os: Visual Studio 2015 RC
clone_folder: c:\projects\open62541
environment:
    global:
        CYG_ROOT: C:/cygwin
before_build:
# Workaround for CMake not wanting sh.exe on PATH for MinGW
- set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
- set PATH=C:\MinGW\bin;%PATH%
# Update Cygwin
- ps: $exePath = "C:\cygwin\setup-x86.exe"; (New-Object Net.WebClient).DownloadFile('https://cygwin.com/setup-x86.exe', $exePath)
build_script: 
- cd c:\projects\open62541
# cygwin cmake stopped working on 05.07.2016 -- commented out until a fix appears
#- md build
#- cd build
#- echo "Testing cygwin"
#- C:\cygwin\setup-x86.exe -q -P cmake,gcc-core,make,python
#- cmd: '%CYG_ROOT%/bin/bash --login -lc "cd /cygdrive/c/projects/open62541/build; cmake -DUA_BUILD_EXAMPLESERVER:BOOL=ON -DUA_BUILD_EXAMPLECLIENT:BOOL=ON -DUA_BUILD_EXAMPLES:BOOL=ON -G\"Unix Makefiles\" ..; make"'
#- cd ..
#- rd /s /q build
- md build
- cd build
- echo "Testing MinGW32"
- cmake -DUA_BUILD_EXAMPLESERVER:BOOL=ON -DUA_BUILD_EXAMPLECLIENT:BOOL=ON -DUA_BUILD_EXAMPLES:BOOL=ON -G"MinGW Makefiles" ..
- mingw32-make
- cd ..
- rd /s /q build
- md build
- cd build
- cmake -DUA_BUILD_EXAMPLESERVER:BOOL=ON -DUA_BUILD_EXAMPLECLIENT:BOOL=ON -DUA_BUILD_EXAMPLES:BOOL=ON -G"Visual Studio 12 2013" ..
- msbuild open62541.sln
- echo "Testing amalgamation"
- cd ..
- rd /s /q build
- md build
- cd build
- cmake -DUA_BUILD_EXAMPLESERVER:BOOL=ON -DUA_BUILD_EXAMPLECLIENT:BOOL=ON -DUA_BUILD_EXAMPLES:BOOL=ON -DUA_ENABLE_AMALGAMATION:BOOL=ON -G"Visual Studio 12 2013" ..
- msbuild open62541.sln 
- copy C:\projects\open62541\build\open62541.c C:\projects\open62541\build\Debug\open62541.c
- copy C:\projects\open62541\build\open62541.h C:\projects\open62541\build\Debug\open62541.h
- cd ..
- echo "Win 64 build"
- md build64
- cd build64
- cmake -DUA_BUILD_EXAMPLESERVER:BOOL=ON -DUA_BUILD_EXAMPLECLIENT:BOOL=ON -DUA_BUILD_EXAMPLES:BOOL=ON -DUA_ENABLE_AMALGAMATION:BOOL=ON -G"Visual Studio 12 2013 Win64" ..
- msbuild open62541.sln 
- copy C:\projects\open62541\build64\open62541.c C:\projects\open62541\build64\Debug\open62541.c
- copy C:\projects\open62541\build64\open62541.h C:\projects\open62541\build64\Debug\open62541.h
- cd ..
after_build:
- 7z a open62541-win32.zip %APPVEYOR_BUILD_FOLDER%\build\Debug\*
- 7z a open62541-win64.zip %APPVEYOR_BUILD_FOLDER%\build64\Debug\*
- appveyor PushArtifact open62541-win32.zip
- appveyor PushArtifact open62541-win64.zip
